require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FaveTweetsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # FaveTweet. As you add validations to FaveTweet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FaveTweetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fave_tweets as @fave_tweets" do
      fave_tweet = FaveTweet.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:fave_tweets)).to eq([fave_tweet])
    end
  end

  describe "GET show" do
    it "assigns the requested fave_tweet as @fave_tweet" do
      fave_tweet = FaveTweet.create! valid_attributes
      get :show, {:id => fave_tweet.to_param}, valid_session
      expect(assigns(:fave_tweet)).to eq(fave_tweet)
    end
  end

  describe "GET new" do
    it "assigns a new fave_tweet as @fave_tweet" do
      get :new, {}, valid_session
      expect(assigns(:fave_tweet)).to be_a_new(FaveTweet)
    end
  end

  describe "GET edit" do
    it "assigns the requested fave_tweet as @fave_tweet" do
      fave_tweet = FaveTweet.create! valid_attributes
      get :edit, {:id => fave_tweet.to_param}, valid_session
      expect(assigns(:fave_tweet)).to eq(fave_tweet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FaveTweet" do
        expect {
          post :create, {:fave_tweet => valid_attributes}, valid_session
        }.to change(FaveTweet, :count).by(1)
      end

      it "assigns a newly created fave_tweet as @fave_tweet" do
        post :create, {:fave_tweet => valid_attributes}, valid_session
        expect(assigns(:fave_tweet)).to be_a(FaveTweet)
        expect(assigns(:fave_tweet)).to be_persisted
      end

      it "redirects to the created fave_tweet" do
        post :create, {:fave_tweet => valid_attributes}, valid_session
        expect(response).to redirect_to(FaveTweet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fave_tweet as @fave_tweet" do
        post :create, {:fave_tweet => invalid_attributes}, valid_session
        expect(assigns(:fave_tweet)).to be_a_new(FaveTweet)
      end

      it "re-renders the 'new' template" do
        post :create, {:fave_tweet => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested fave_tweet" do
        fave_tweet = FaveTweet.create! valid_attributes
        put :update, {:id => fave_tweet.to_param, :fave_tweet => new_attributes}, valid_session
        fave_tweet.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested fave_tweet as @fave_tweet" do
        fave_tweet = FaveTweet.create! valid_attributes
        put :update, {:id => fave_tweet.to_param, :fave_tweet => valid_attributes}, valid_session
        expect(assigns(:fave_tweet)).to eq(fave_tweet)
      end

      it "redirects to the fave_tweet" do
        fave_tweet = FaveTweet.create! valid_attributes
        put :update, {:id => fave_tweet.to_param, :fave_tweet => valid_attributes}, valid_session
        expect(response).to redirect_to(fave_tweet)
      end
    end

    describe "with invalid params" do
      it "assigns the fave_tweet as @fave_tweet" do
        fave_tweet = FaveTweet.create! valid_attributes
        put :update, {:id => fave_tweet.to_param, :fave_tweet => invalid_attributes}, valid_session
        expect(assigns(:fave_tweet)).to eq(fave_tweet)
      end

      it "re-renders the 'edit' template" do
        fave_tweet = FaveTweet.create! valid_attributes
        put :update, {:id => fave_tweet.to_param, :fave_tweet => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fave_tweet" do
      fave_tweet = FaveTweet.create! valid_attributes
      expect {
        delete :destroy, {:id => fave_tweet.to_param}, valid_session
      }.to change(FaveTweet, :count).by(-1)
    end

    it "redirects to the fave_tweets list" do
      fave_tweet = FaveTweet.create! valid_attributes
      delete :destroy, {:id => fave_tweet.to_param}, valid_session
      expect(response).to redirect_to(fave_tweets_url)
    end
  end

end
